spring.application.name=cours
spring.cloud.config.enabled=false
# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource
spring.datasource.username=Amine
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/Cours
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = create
server.port=8092
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

# File upload configuration
upload.dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB