spring.application.name=Gateway
server.port=8093

# Eureka registration
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/JobBoardKeycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:8180/realms/JobBoardKeycloak/protocol/openid-connect/certs
# Gateway Routes for Etudiant Microservice
spring.cloud.gateway.routes[0].id=etudiant
spring.cloud.gateway.routes[0].uri=lb://ETUDIANT
spring.cloud.gateway.routes[0].predicates[0]=Path=/etudiants/**

spring.cloud.gateway.routes[1].id=inscription
spring.cloud.gateway.routes[1].uri=lb://ETUDIANT
spring.cloud.gateway.routes[1].predicates[0]=Path=/inscriptions/**

spring.cloud.gateway.routes[2].id=note
spring.cloud.gateway.routes[2].uri=lb://ETUDIANT
spring.cloud.gateway.routes[2].predicates[0]=Path=/notes/**

# Global CORS configuration for Spring Cloud Gateway
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
