spring.application.name=Gateway
server.port=8093

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway Routes for Etudiant Microservice (running on port 8092)
spring.cloud.gateway.routes[0].id=etudiant
spring.cloud.gateway.routes[0].uri=http://localhost:8092
spring.cloud.gateway.routes[0].predicates[0]=Path=/etudiants/**

spring.cloud.gateway.routes[1].id=inscription
spring.cloud.gateway.routes[1].uri=http://localhost:8092
spring.cloud.gateway.routes[1].predicates[0]=Path=/inscriptions/**

spring.cloud.gateway.routes[2].id=note
spring.cloud.gateway.routes[2].uri=http://localhost:8092
spring.cloud.gateway.routes[2].predicates[0]=Path=/notes/**
